// import { Inter } from 'next/font/google';
import { Urbanist, Nunito } from 'next/font/google';
const urbanist = Urbanist({ subsets: ['latin'] });
// const nunito = Nunito({ subsets: ['latin'] });
import './main.scss';
import Nav from './components/Nav';
import Footer from './components/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
// console.log(nunito.className);
export default function RootLayout({ children }) {
  return (
    <html className={urbanist.className} lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
